repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]

      - id: ruff-format
        types_or: [python, pyi, jupyter]

exclude: ^assets/
