[project]
name = "personal-website"
version = "0.1.0"
description = "Repository for my personal website build using Reflex."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "reflex[db]==0.9.7",
]

[dependency-groups]
dev = [
    "graphviz>=0.20.3",
    "jupyter>=1.1.1",
    "marimo>=0.19.2",
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "pre-commit>=4.1.0",
    "pynvim>=0.5.2",
    "ruff>=0.9.7",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "stargazer>=0.0.7",
    "statsmodels>=0.14.4",
    "sympy>=1.13.3",
    "plotly>=6.0.0",
    "kaleido<0.2.1",
    "quarto-cli>=1.8.26",
    "jupyter-cache>=1.0.1",
    "lintquarto>=0.7.0",
]

[tool.marimo.runtime]
output_max_bytes = 20_000_000

[tool.ruff]
exclude = ["assets/articles/notebooks"]
