name: integration-tests

env:
  TELEMETRY_ENABLED: false
  REFLEX_DEP: "git+https://github.com/reflex-dev/reflex@main"
on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      reflex_dep:
        description: "Reflex dependency (full specifier)"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  reflex-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.21"

      - name: Install project dependencies
        run: uv sync
      - name: Install Requirements for personal_website and reflex
        run: uv pip install '${{ github.event.inputs.reflex_dep || env.REFLEX_DEP }}'
      - name: Init Website for personal_website
        run: reflex init
      - name: Export the website
        run: reflex export
      - name: Test Docker Build
        run: docker build .
