name: regression-tests

on:
  pull_request:
    branches: ["*"]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  reflex-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.21"

      - name: Install project dependencies
        run: uv sync
      - name: Init Website for personal_website
        shell: bash
        run: source .venv/bin/activate && reflex init
      - name: Export the website
        shell: bash
        run: source .venv/bin/activate && reflex export
      - name: Test Docker Build
        shell: bash
        run: source .venv/bin/activate && docker build . -f main.Dockerfile
